---

# by using this playbook, you will be able to
# setup tree command on the target hosts

- hosts: all
  become: true
  tasks:
    - name: Install tree command
      apt:
        name: tree
        state: present
        update_cache: yes
